### ISSUE TITLE
GetStopInfo does not work correctly

### ISSUE THREAD

**Issue by breezy876** [ipax77/pax.uciChessEngine#1]
Hello. Firstly, great work on this! I have found it very useful :)

Now my issue. Looking at the code in GetStopInfo, it is supposed to fire the MoveReady event.

My code adds a handler for this event and it works on every "go". See below.

   ```
 engine = new Engine(EngineName, enginePath);
 engine.Status.MoveReady += Status_MoveReady;

await engine.Start();
await engine.IsReady();

```

The event shown above gets fired in my own code whenever I call , "go". So that works.

However, when I call GetStopInfo , which is supposed to send "stop" and should immediately should force the engine to compute the best move, it does not immediately return as it should; there is a long delay. Furthermore, the MoveReady event does not get fired and the EngineInfo instance returned by GetStopInfo does not contain the BestMove

I am calling GetStopInfo like so in my own code

```
        public async Task Stop()
        {
            if (!IsStarted())
                return;

            var info = await engine.GetStopInfo();
}
```

So as it stands, I am unable to interrupt the computation with this library. Sending "stop" to the engine does not work, either as in the MoveReady event also doesn't get fired. I find this very strange as looking at the StatusService code, when it sees "bestmove", it should fire the MoveReady event (as it does with "go"). I tried this also with no success. Any help would be appreciated. Thanks

**Comment by ipax77** [comment]
Hey, thank you for your kind words :)
I added a [StopInfoTest](https://github.com/ipax77/pax.uciChessEngine/blob/master/pax.uciChessEngine.tests/EngineTests.cs#L91)
This is working as expected. If you find time, can you provide a Test that is failing, please? After "go" you have to wait a bit until the engine get's the info and starts processing (200ms should be sufficient in most scenarios).

**Comment by breezy876** [comment]
Hello. No problem, I give credit where it is due. Thanks for the speedy response. I have solved the problem. It was in my own code. 

The test works. However, it did not work this way in my code for some reason. It still behaved as I mentioned. I am using two separate tasks: one to compute the bestmove and send "go", the other to call GetStopInfo. See as follows:

  public async Task Go(
            long whiteTime,
            long blackTime,
            int depth,
            bool useFixedDepth = false)
        {
            if (!IsStarted())
                return;

            if (useFixedDepth)
                await engine.Send($"go depth {depth}");
            else
                await engine.Send($"go wtime {whiteTime} btime {blackTime}");
        }
     public async Task Stop()
       {
           if (!IsStarted())
               return;

           var info = await engine.GetStopInfo();
       }

The Go Task works as expected. The MoveReady event gets fired whenever "bestmove" is seen by the engine- as shown in the StatusService. However the Stop task did not return the best move in the info variable , it was null and it did not immediately return - it took several seconds. The MoveReady event also did not get fired. The handler is attached in the following code (also in another Task).

  public async Task Start(string enginePath)
     {
         EnginePath = enginePath;
         EngineName = Path.GetFileNameWithoutExtension(enginePath);

         engineConfigFilePath = Path.Combine(Path.GetDirectoryName(enginePath), $"{EngineName}.json");

         Status = EngineStatus.Starting;
         engine = new Engine(EngineName, enginePath);
         engine.Status.MoveReady += Status_MoveReady;

         await engine.Start();
         await engine.IsReady();

         Status = EngineStatus.Started;
         Options = CreateOptions(await engine.GetOptions());//populate with default options

         if (File.Exists(engineConfigFilePath))//load engine options json
         {
             await LoadOptions();
             await UpdateOptions();
         }

         EngineStarted.Invoke(this, EventArgs.Empty);
     }
above code also worked as expected.

I was confused at first but then realised it was because I am calling both Stop and Go from separate threads (event handlers) in both a Windows Forms timer event and a button click event (to send the Stop), which for some reason did not like async/await. Removing the await and async in the button click solved the problem.

Thanks for your help :)

**Comment by ipax77** [comment]
You are welcome, glad to hear that you solved your problem :)
